### ISSUE TITLE
v3 .replaceAll breaks support for Node v14

### ISSUE THREAD

**Issue by ricky-davis** [ldapjs/node-ldapjs#843]
For security requirements at work I must use Node v14.21.3. 
This line in client.js breaks compatibility with versions of Node older than v15.
https://github.com/ldapjs/node-ldapjs/blob/67617fee4f24816fc60004f0ff7252548a784969/lib/client/client.js#L1252

Following the help here: https://stackoverflow.com/questions/1144783/how-do-i-replace-all-occurrences-of-a-string-in-javascript

I've added the function 
```javascript
function escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```
and changed the line to
```javascript
event = (event[0].toLowerCase() + event.slice(1)).replace(new RegExp(escapeRegExp('Result'), 'g'), '');
```
And it seems to work fine, but I'm not sure all the test cases it may need.

**Comment by jsumners** [comment]
Node.js v14 goes end-of-life on 2023-04-30 (https://github.com/nodejs/release#release-schedule). We decided to drop support for it in `ldapjs@3` so that we don't have to release `ldapjs@4` in such a short amount of time.

You can view the releases we actively support at https://github.com/ldapjs/node-ldapjs/blob/6ba15ed672fd1942c2e8a846a68decf9e915c959/.github/workflows/main.yml#L34-L37

The readme should be updated to indicate where to view our supported Node.js versions can be found.
