### ISSUE TITLE
package.json does not specify an engine 

### ISSUE THREAD

**Issue by CodeBroJohn** [ldapjs/node-ldapjs#857]
Looks like packages that require this as a dependency are picking up the latest version even for versions of nodejs that are not compatible. I think this may be happening because the latest version does not specify an engine.

**Comment by jsumners** [comment]
No, it is happening because the modules you are installing which depend upon this one are not using the correct semver qualifier. See https://docs.npmjs.com/cli/v6/using-npm/semver#ranges

The `engines` field does nothing:

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines
> Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

You'll need to open an issue with the packages you rely upon asking them to fix their dependencies list.
