### ISSUE TITLE
Retrieving distinguished names from ad is not straightforward

### ISSUE THREAD

**Issue by simon-lorenz** [ldapjs/node-ldapjs#904]
While migrating to v3 I noticed some quirks when retrieving distinguished names from active directory:

1. `dn` is not included in `SearchEntry.attributes`, even if it's specified in `SearchOptions.attributes`.
2. `SearchEntry.dn` is documented as a string but it's actually an object
3. I could not find any documentation about the properties of `SearchEntry` aside from the source code. I was especially confused about `entry.dn` vs `entry.objectName` (aliases, both of type `object`) vs `entry.pojo.objectName` (`string`) vs `entry.pojo.dn` (`undefined`).

Thank you for your hard work!

```js
const ldapClient = ldap.createClient({
	url: 'localhost'
})

const opts = {
	filter: "(userPrincipalName=example)",
	scope: 'sub',
	attributes: [
		'objectGUID;binary',
		'sAMAccountName',
		'dn', // <---
		'sn',
		'givenName',
		'mail'
	]
}

ldapClient.search('DC=company,DC=domain', opts, (err, res) => {
	res.on(
		'searchEntry',
		/**
		 * @param {import('ldapjs').SearchEntry} entry
		 */
		entry => {
			entry.attributes.find(attr => attr.type === 'dn') // => undefined

			entry.dn // intellisense tells me this property is a string, but it's actually an object

			console.log("dn: " + entry.dn) // dn: CN=Firstname Lastname,OU=...
			console.log(typeof entry.dn) // object

			const obj = { dn: entry.dn } 
			// => { dn: {} } instead of { dn: "CN=Firstname Lastname,OU=..." }
			// I fixed this by explicitly calling entry.dn.toString()
		}
	)
})
```

**Comment by jsumners** [comment]
> 1. `dn` is not included in `SearchEntry.attributes`, even if it's specified in `SearchOptions.attributes`.

The `dn` is the path to entity (https://ldap.com/ldap-dns-and-rdns/). It is not typically an actual attribute on the entity. Verify if your LDAP schema defines `dn` as an attribute.

> 2\. `SearchEntry.dn` is documented as a string but it's actually an object

Please link to the documentation in question. It is very likely that the documentation needs to be updated. Would you like to send a PR doing so?

> 3\. I could not find any documentation about the properties of `SearchEntry` aside from the source code. I was especially confused about `entry.dn` vs `entry.objectName` (aliases, both of type `object`) vs `entry.pojo.objectName` (`string`) vs `entry.pojo.dn` (`undefined`).

It's not great practice, I know, but in an effort to get v3 shipped, I skipped creating Makdown documents for all of the modules and objects. I did provide thorough jsdoc throughout them, and feel like that is a good middle ground. So, yes, it is correct to consult the source code for the the documentation around these objects.

The objects in v3 follow the LDAP specifications. In regard to the `SearchEntry` object, see https://ldap.com/ldapv3-wire-protocol-reference-search/#search-result-entry. The spec defines `objectName` as the LDAP DN for that entry. In ldapjs v3, that is represented by a DN object. DN objects support `.toString()`, as you have noted, in order to access the string form of the DN.

The `.pojo` accessor is meant to serialize LDAP objects into "plain JavaScript objects", i.e. "JSON" representations. This can be an expensive operation. I recommend using the `attributes` accessor to directly access the objects. As an example, doing so will give you the standard array iterator methods for each attribute.

**Comment by simon-lorenz** [comment]
> The dn is the path to entity (https://ldap.com/ldap-dns-and-rdns/). It is not typically an actual attribute on the entity. Verify if your LDAP schema defines dn as an attribute.

That makes sense. I'm not terribly familiar with ldap so I assumed `dn` was just another attribute. I removed `dn` from `SearchOptions.attributes` entirely and everything still works. 

> Please link to the documentation in question. It is very likely that the documentation needs to be updated. Would you like to send a PR doing so?

I think the problem is [this JSDoc annotation](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/ldap-message.js#L141). It should probably say `@type {import('@ldapjs/dn').DN}` just like above the `#objectName` prop in [`searchResultEntry.js`](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/messages/search-result-entry.js#L16). 

I could send a PR, but there are other subclasses that implement `get _dn()` differently. Some [actually return a string](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/messages/bind-request.js#L93), others [may also return `null`](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/messages/add-request.js#L114). So I'm not entirely sure how to annotate correctly.

Thanks for your other explanations regarding LDAP specifications and `.pojo`, those were also very helpful!

**Comment by jsumners** [comment]
> I think the problem is [this JSDoc annotation](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/ldap-message.js#L141). It should probably say `@type {import('@ldapjs/dn').DN}` just like above the `#objectName` prop in [`searchResultEntry.js`](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/messages/search-result-entry.js#L16).

That's definitely a mistake. You are correct in what it should be.

> Some [actually return a string](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/messages/bind-request.js#L93),

This is a backward compatibility method. Any method starting with `_` should be considered private.

> others [may also return `null`](https://github.com/ldapjs/messages/blob/e0b8f8f5617f8e1880717e6ef8e5da1a5f7adb0e/lib/messages/add-request.js#L114).

Same thing.

> So I'm not entirely sure how to annotate correctly.

We should correct the docblock on the public `.dn` accessor.

**Comment by jsumners** [comment]
Fixed via linked PR.
