### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by eirikhanasand** [ldapjs/node-ldapjs#963]
When trying to use this dependency I get 
```ts
node:util - Error: Module build failed: UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```
It seems the issue occurs everywhere node:util is used. Is there any fix planned or workaround available?

Specifically I am trying to use the createClient function like so:
```ts
import { createClient } from 'ldapjs'

export default async function Auth(username: string, password: string): Promise<boolean> {
    const client = createClient({ url: 'ldaps://domain.example.com' })
    // more code here, but its the above line that creates the error (the error comes when createClient is accessed)
 }

**Comment by jsumners** [comment]
Thank you for the report, but we do not support bundlers of any sort.

**Comment by eirikhanasand** [comment]
Hello, I dont see how bundlers are relevant. I am not trying to use a bundler, simply trying to run the createClient function normally, but it gives this bug that leaves me unable to use the dependency (it doesnt work because it crashes  during build). If the project team does not have plans to resolve this, could you still leave it open so the community can help me out?

**Comment by jsumners** [comment]
> Hello, I dont see how bundlers are relevant. I am not trying to use a bundler

The error clearly shows that the issue arrises from Webpack. It also does not make any sense because there isn't any code (currently) in this organization that uses the `node:` prefix when requiring modules:

https://github.com/search?q=org%3Aldapjs+%22node%3Autil%22&type=code

> Despite the project team not having plans to resolve this, could you still leave it open so the community can help me out?

The community is welcome to work on any issues that affect them. For one such as this, that would entail adding a continuous integration configuration that proves the library works with bundlers. However, I will say that such a contribution would need to be _extremely_ easy to maintain. I am simply not interested in maintaining bundler compatibility and I think it very likely that any such contributor will move on after having made the contribution.

> Or provide an example of how to use this correctly?

The code snippet provided seems correct to me, but there is not much context in it so I cannot say that with 100% surety.

**Comment by eirikhanasand** [comment]
Thank you for helping. I will debug further meself and see if I can find the source of the problem. It seems that it somehow kicks in when I activate this repository, despite it not being directly related.
